  main = ".open-next/worker.js"
  name = 'rph-webui'
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]

  routes = [
    { pattern = "rph.zacklack.de", custom_domain = true }
  ]

  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [observability.logs]
  enabled = true